version: "3.8"

services:
  # Jenkins Master
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"    # for agent connections
    user: root         # so Jenkins can run Docker inside the container
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/var/jenkins_home/.docker/config.json:ro

volumes:
  jenkins_home:
