version: "3.8"
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - ./services/devops/teamcity/data:/data/teamcity_server/datadir
      - ./services/devops/teamcity/logs:/opt/teamcity/logs

  teamcity-agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent
    environment:
      - SERVER_URL=http://localhost:8111
    depends_on:
      - teamcity-server
